# MySQL.  Versions 4.1 and 5.0 are recommended.
#
# Install the MYSQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html

development:
  adapter: mysql2
  encoding: utf8
  collation: utf8_unicode_ci
  reconnect: false
  database: <%= ENV['RAILS_DATABASE_NAME'] || 'scenic-test' %>
  pool: 5
  username: <%= ENV['RAILS_DATABASE_USERNAME'] || 'root' %>
  password: <%= ENV['RAILS_DATABASE_PASSWORD'] %>
  host: <%= ENV['RAILS_DATABASE_HOST'] || 'localhost' %>
  port: <%= ENV['RAILS_DATABASE_PORT'] || 3306 %>

test:
  adapter: mysql2
  encoding: utf8
  collation: utf8_unicode_ci
  reconnect: false
  database: scenic-test-test
  pool: 5
  username: <%= ENV['RAILS_DATABASE_USERNAME'] || 'root' %>
  password: <%= ENV['RAILS_DATABASE_PASSWORD'] %>
  host: <%= ENV['RAILS_DATABASE_HOST'] || 'localhost' %>
  port: <%= ENV['RAILS_DATABASE_PORT'] || 3306 %>
